# Generated by Django 4.1.3 on 2022-12-04 05:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_profile_user"),
        ("post", "0002_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likesCount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("owner", "post")},
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                ("content", models.TextField()),
                ("likesCount", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.post"
                    ),
                ),
            ],
        ),
    ]
