# Generated by Django 4.1.3 on 2022-12-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="bio",
            new_name="about",
        ),
        migrations.AddField(
            model_name="profile",
            name="tagline",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=300),
        ),
    ]
