# Generated by Django 4.1.3 on 2022-12-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_bio_profile_about_profile_tagline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
